// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensor_log_message.proto

package com.javed.logs.lambda;

public final class SensorLogProtos {
  private SensorLogProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SensorLogMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sensor.log.message.SensorLogMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .google.protobuf.Timestamp time_stamp = 1;</code>
     */
    boolean hasTimeStamp();
    /**
     * <code>optional .google.protobuf.Timestamp time_stamp = 1;</code>
     */
    com.google.protobuf.Timestamp getTimeStamp();
    /**
     * <code>optional .google.protobuf.Timestamp time_stamp = 1;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimeStampOrBuilder();

    /**
     * <code>optional int32 sensor_id = 2;</code>
     */
    boolean hasSensorId();
    /**
     * <code>optional int32 sensor_id = 2;</code>
     */
    int getSensorId();

    /**
     * <code>optional .sensor.log.message.SensorLogMessage.EventType event_type = 3;</code>
     */
    boolean hasEventType();
    /**
     * <code>optional .sensor.log.message.SensorLogMessage.EventType event_type = 3;</code>
     */
    SensorLogMessage.EventType getEventType();

    /**
     * <code>optional string event_message = 4;</code>
     */
    boolean hasEventMessage();
    /**
     * <code>optional string event_message = 4;</code>
     */
    String getEventMessage();
    /**
     * <code>optional string event_message = 4;</code>
     */
    com.google.protobuf.ByteString
        getEventMessageBytes();
  }
  /**
   * <pre>
   **
   * Although the fields described in the message below are marked as optional,
   * they are considered to be mandatory fields in the application.
   * They are not marked as required due to the recommendation by Google
   * on avoiding required fields as they cause more harm than good when
   * there is a change required in future to the data structure.
   * </pre>
   *
   * Protobuf type {@code sensor.log.message.SensorLogMessage}
   */
  public  static final class SensorLogMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sensor.log.message.SensorLogMessage)
      SensorLogMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SensorLogMessage.newBuilder() to construct.
    private SensorLogMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SensorLogMessage() {
      eventType_ = 0;
      eventMessage_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SensorLogMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = timeStamp_.toBuilder();
              }
              timeStamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(timeStamp_);
                timeStamp_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sensorId_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              EventType value = EventType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                eventType_ = rawValue;
              }
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              eventMessage_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SensorLogProtos.internal_static_sensor_log_message_SensorLogMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SensorLogProtos.internal_static_sensor_log_message_SensorLogMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SensorLogMessage.class, Builder.class);
    }

    /**
     * Protobuf enum {@code sensor.log.message.SensorLogMessage.EventType}
     */
    public enum EventType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ERROR = 0;</code>
       */
      ERROR(0),
      /**
       * <code>INFORMATION = 1;</code>
       */
      INFORMATION(1),
      /**
       * <code>WARNING = 2;</code>
       */
      WARNING(2),
      ;

      /**
       * <code>ERROR = 0;</code>
       */
      public static final int ERROR_VALUE = 0;
      /**
       * <code>INFORMATION = 1;</code>
       */
      public static final int INFORMATION_VALUE = 1;
      /**
       * <code>WARNING = 2;</code>
       */
      public static final int WARNING_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static EventType valueOf(int value) {
        return forNumber(value);
      }

      public static EventType forNumber(int value) {
        switch (value) {
          case 0: return ERROR;
          case 1: return INFORMATION;
          case 2: return WARNING;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EventType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          EventType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
              public EventType findValueByNumber(int number) {
                return EventType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return SensorLogMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final EventType[] VALUES = values();

      public static EventType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private EventType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:sensor.log.message.SensorLogMessage.EventType)
    }

    private int bitField0_;
    public static final int TIME_STAMP_FIELD_NUMBER = 1;
    private com.google.protobuf.Timestamp timeStamp_;
    /**
     * <code>optional .google.protobuf.Timestamp time_stamp = 1;</code>
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .google.protobuf.Timestamp time_stamp = 1;</code>
     */
    public com.google.protobuf.Timestamp getTimeStamp() {
      return timeStamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timeStamp_;
    }
    /**
     * <code>optional .google.protobuf.Timestamp time_stamp = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimeStampOrBuilder() {
      return timeStamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timeStamp_;
    }

    public static final int SENSOR_ID_FIELD_NUMBER = 2;
    private int sensorId_;
    /**
     * <code>optional int32 sensor_id = 2;</code>
     */
    public boolean hasSensorId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 sensor_id = 2;</code>
     */
    public int getSensorId() {
      return sensorId_;
    }

    public static final int EVENT_TYPE_FIELD_NUMBER = 3;
    private int eventType_;
    /**
     * <code>optional .sensor.log.message.SensorLogMessage.EventType event_type = 3;</code>
     */
    public boolean hasEventType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .sensor.log.message.SensorLogMessage.EventType event_type = 3;</code>
     */
    public EventType getEventType() {
      @SuppressWarnings("deprecation")
      EventType result = EventType.valueOf(eventType_);
      return result == null ? EventType.ERROR : result;
    }

    public static final int EVENT_MESSAGE_FIELD_NUMBER = 4;
    private volatile Object eventMessage_;
    /**
     * <code>optional string event_message = 4;</code>
     */
    public boolean hasEventMessage() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string event_message = 4;</code>
     */
    public String getEventMessage() {
      Object ref = eventMessage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          eventMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string event_message = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEventMessageBytes() {
      Object ref = eventMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        eventMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getTimeStamp());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, sensorId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeEnum(3, eventType_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, eventMessage_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTimeStamp());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sensorId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, eventType_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, eventMessage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SensorLogMessage)) {
        return super.equals(obj);
      }
      SensorLogMessage other = (SensorLogMessage) obj;

      if (hasTimeStamp() != other.hasTimeStamp()) return false;
      if (hasTimeStamp()) {
        if (!getTimeStamp()
            .equals(other.getTimeStamp())) return false;
      }
      if (hasSensorId() != other.hasSensorId()) return false;
      if (hasSensorId()) {
        if (getSensorId()
            != other.getSensorId()) return false;
      }
      if (hasEventType() != other.hasEventType()) return false;
      if (hasEventType()) {
        if (eventType_ != other.eventType_) return false;
      }
      if (hasEventMessage() != other.hasEventMessage()) return false;
      if (hasEventMessage()) {
        if (!getEventMessage()
            .equals(other.getEventMessage())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTimeStamp()) {
        hash = (37 * hash) + TIME_STAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimeStamp().hashCode();
      }
      if (hasSensorId()) {
        hash = (37 * hash) + SENSOR_ID_FIELD_NUMBER;
        hash = (53 * hash) + getSensorId();
      }
      if (hasEventType()) {
        hash = (37 * hash) + EVENT_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + eventType_;
      }
      if (hasEventMessage()) {
        hash = (37 * hash) + EVENT_MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getEventMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SensorLogMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SensorLogMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SensorLogMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SensorLogMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SensorLogMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SensorLogMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SensorLogMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SensorLogMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SensorLogMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SensorLogMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SensorLogMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SensorLogMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SensorLogMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     * Although the fields described in the message below are marked as optional,
     * they are considered to be mandatory fields in the application.
     * They are not marked as required due to the recommendation by Google
     * on avoiding required fields as they cause more harm than good when
     * there is a change required in future to the data structure.
     * </pre>
     *
     * Protobuf type {@code sensor.log.message.SensorLogMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sensor.log.message.SensorLogMessage)
        SensorLogMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SensorLogProtos.internal_static_sensor_log_message_SensorLogMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SensorLogProtos.internal_static_sensor_log_message_SensorLogMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SensorLogMessage.class, Builder.class);
      }

      // Construct using com.javed.logs.lambda.SensorLogProtos.SensorLogMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTimeStampFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (timeStampBuilder_ == null) {
          timeStamp_ = null;
        } else {
          timeStampBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        sensorId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        eventType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        eventMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SensorLogProtos.internal_static_sensor_log_message_SensorLogMessage_descriptor;
      }

      @Override
      public SensorLogMessage getDefaultInstanceForType() {
        return SensorLogMessage.getDefaultInstance();
      }

      @Override
      public SensorLogMessage build() {
        SensorLogMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public SensorLogMessage buildPartial() {
        SensorLogMessage result = new SensorLogMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (timeStampBuilder_ == null) {
            result.timeStamp_ = timeStamp_;
          } else {
            result.timeStamp_ = timeStampBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.sensorId_ = sensorId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.eventType_ = eventType_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.eventMessage_ = eventMessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SensorLogMessage) {
          return mergeFrom((SensorLogMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SensorLogMessage other) {
        if (other == SensorLogMessage.getDefaultInstance()) return this;
        if (other.hasTimeStamp()) {
          mergeTimeStamp(other.getTimeStamp());
        }
        if (other.hasSensorId()) {
          setSensorId(other.getSensorId());
        }
        if (other.hasEventType()) {
          setEventType(other.getEventType());
        }
        if (other.hasEventMessage()) {
          bitField0_ |= 0x00000008;
          eventMessage_ = other.eventMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SensorLogMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SensorLogMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Timestamp timeStamp_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timeStampBuilder_;
      /**
       * <code>optional .google.protobuf.Timestamp time_stamp = 1;</code>
       */
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .google.protobuf.Timestamp time_stamp = 1;</code>
       */
      public com.google.protobuf.Timestamp getTimeStamp() {
        if (timeStampBuilder_ == null) {
          return timeStamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timeStamp_;
        } else {
          return timeStampBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp time_stamp = 1;</code>
       */
      public Builder setTimeStamp(com.google.protobuf.Timestamp value) {
        if (timeStampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timeStamp_ = value;
          onChanged();
        } else {
          timeStampBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp time_stamp = 1;</code>
       */
      public Builder setTimeStamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timeStampBuilder_ == null) {
          timeStamp_ = builderForValue.build();
          onChanged();
        } else {
          timeStampBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp time_stamp = 1;</code>
       */
      public Builder mergeTimeStamp(com.google.protobuf.Timestamp value) {
        if (timeStampBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              timeStamp_ != null &&
              timeStamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            timeStamp_ =
              com.google.protobuf.Timestamp.newBuilder(timeStamp_).mergeFrom(value).buildPartial();
          } else {
            timeStamp_ = value;
          }
          onChanged();
        } else {
          timeStampBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp time_stamp = 1;</code>
       */
      public Builder clearTimeStamp() {
        if (timeStampBuilder_ == null) {
          timeStamp_ = null;
          onChanged();
        } else {
          timeStampBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp time_stamp = 1;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTimeStampBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getTimeStampFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.Timestamp time_stamp = 1;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimeStampOrBuilder() {
        if (timeStampBuilder_ != null) {
          return timeStampBuilder_.getMessageOrBuilder();
        } else {
          return timeStamp_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : timeStamp_;
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp time_stamp = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTimeStampFieldBuilder() {
        if (timeStampBuilder_ == null) {
          timeStampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTimeStamp(),
                  getParentForChildren(),
                  isClean());
          timeStamp_ = null;
        }
        return timeStampBuilder_;
      }

      private int sensorId_ ;
      /**
       * <code>optional int32 sensor_id = 2;</code>
       */
      public boolean hasSensorId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 sensor_id = 2;</code>
       */
      public int getSensorId() {
        return sensorId_;
      }
      /**
       * <code>optional int32 sensor_id = 2;</code>
       */
      public Builder setSensorId(int value) {
        bitField0_ |= 0x00000002;
        sensorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sensor_id = 2;</code>
       */
      public Builder clearSensorId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sensorId_ = 0;
        onChanged();
        return this;
      }

      private int eventType_ = 0;
      /**
       * <code>optional .sensor.log.message.SensorLogMessage.EventType event_type = 3;</code>
       */
      public boolean hasEventType() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .sensor.log.message.SensorLogMessage.EventType event_type = 3;</code>
       */
      public EventType getEventType() {
        @SuppressWarnings("deprecation")
        EventType result = EventType.valueOf(eventType_);
        return result == null ? EventType.ERROR : result;
      }
      /**
       * <code>optional .sensor.log.message.SensorLogMessage.EventType event_type = 3;</code>
       */
      public Builder setEventType(EventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        eventType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .sensor.log.message.SensorLogMessage.EventType event_type = 3;</code>
       */
      public Builder clearEventType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        eventType_ = 0;
        onChanged();
        return this;
      }

      private Object eventMessage_ = "";
      /**
       * <code>optional string event_message = 4;</code>
       */
      public boolean hasEventMessage() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string event_message = 4;</code>
       */
      public String getEventMessage() {
        Object ref = eventMessage_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            eventMessage_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string event_message = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEventMessageBytes() {
        Object ref = eventMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          eventMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string event_message = 4;</code>
       */
      public Builder setEventMessage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        eventMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string event_message = 4;</code>
       */
      public Builder clearEventMessage() {
        bitField0_ = (bitField0_ & ~0x00000008);
        eventMessage_ = getDefaultInstance().getEventMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string event_message = 4;</code>
       */
      public Builder setEventMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        eventMessage_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sensor.log.message.SensorLogMessage)
    }

    // @@protoc_insertion_point(class_scope:sensor.log.message.SensorLogMessage)
    private static final SensorLogMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SensorLogMessage();
    }

    public static SensorLogMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<SensorLogMessage>
        PARSER = new com.google.protobuf.AbstractParser<SensorLogMessage>() {
      @Override
      public SensorLogMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SensorLogMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SensorLogMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SensorLogMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public SensorLogMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensor_log_message_SensorLogMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensor_log_message_SensorLogMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030sensor_log_message.proto\022\022sensor.log.m" +
      "essage\032\037google/protobuf/timestamp.proto\"" +
      "\346\001\n\020SensorLogMessage\022.\n\ntime_stamp\030\001 \001(\013" +
      "2\032.google.protobuf.Timestamp\022\021\n\tsensor_i" +
      "d\030\002 \001(\005\022B\n\nevent_type\030\003 \001(\0162..sensor.log" +
      ".message.SensorLogMessage.EventType\022\025\n\re" +
      "vent_message\030\004 \001(\t\"4\n\tEventType\022\t\n\005ERROR" +
      "\020\000\022\017\n\013INFORMATION\020\001\022\013\n\007WARNING\020\002B(\n\025com." +
      "javed.logs.lambdaB\017SensorLogProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_sensor_log_message_SensorLogMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sensor_log_message_SensorLogMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensor_log_message_SensorLogMessage_descriptor,
        new String[] { "TimeStamp", "SensorId", "EventType", "EventMessage", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
