/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.sensor.log.message.SensorLogMessage', null, global);
goog.exportSymbol('proto.sensor.log.message.SensorLogMessage.EventType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sensor.log.message.SensorLogMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sensor.log.message.SensorLogMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sensor.log.message.SensorLogMessage.displayName = 'proto.sensor.log.message.SensorLogMessage';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sensor.log.message.SensorLogMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.sensor.log.message.SensorLogMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sensor.log.message.SensorLogMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensor.log.message.SensorLogMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    timeStamp: (f = msg.getTimeStamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    sensorId: jspb.Message.getField(msg, 2),
    eventType: jspb.Message.getField(msg, 3),
    eventMessage: jspb.Message.getField(msg, 4)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sensor.log.message.SensorLogMessage}
 */
proto.sensor.log.message.SensorLogMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sensor.log.message.SensorLogMessage;
  return proto.sensor.log.message.SensorLogMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sensor.log.message.SensorLogMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sensor.log.message.SensorLogMessage}
 */
proto.sensor.log.message.SensorLogMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimeStamp(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSensorId(value);
      break;
    case 3:
      var value = /** @type {!proto.sensor.log.message.SensorLogMessage.EventType} */ (reader.readEnum());
      msg.setEventType(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setEventMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sensor.log.message.SensorLogMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sensor.log.message.SensorLogMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sensor.log.message.SensorLogMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensor.log.message.SensorLogMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimeStamp();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = /** @type {!proto.sensor.log.message.SensorLogMessage.EventType} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.sensor.log.message.SensorLogMessage.EventType = {
  ERROR: 0,
  INFORMATION: 1,
  WARNING: 2
};

/**
 * optional google.protobuf.Timestamp time_stamp = 1;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.sensor.log.message.SensorLogMessage.prototype.getTimeStamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 1));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.sensor.log.message.SensorLogMessage.prototype.setTimeStamp = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.sensor.log.message.SensorLogMessage.prototype.clearTimeStamp = function() {
  this.setTimeStamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensor.log.message.SensorLogMessage.prototype.hasTimeStamp = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 sensor_id = 2;
 * @return {number}
 */
proto.sensor.log.message.SensorLogMessage.prototype.getSensorId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.sensor.log.message.SensorLogMessage.prototype.setSensorId = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sensor.log.message.SensorLogMessage.prototype.clearSensorId = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensor.log.message.SensorLogMessage.prototype.hasSensorId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional EventType event_type = 3;
 * @return {!proto.sensor.log.message.SensorLogMessage.EventType}
 */
proto.sensor.log.message.SensorLogMessage.prototype.getEventType = function() {
  return /** @type {!proto.sensor.log.message.SensorLogMessage.EventType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.sensor.log.message.SensorLogMessage.EventType} value */
proto.sensor.log.message.SensorLogMessage.prototype.setEventType = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sensor.log.message.SensorLogMessage.prototype.clearEventType = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensor.log.message.SensorLogMessage.prototype.hasEventType = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string event_message = 4;
 * @return {string}
 */
proto.sensor.log.message.SensorLogMessage.prototype.getEventMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.sensor.log.message.SensorLogMessage.prototype.setEventMessage = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sensor.log.message.SensorLogMessage.prototype.clearEventMessage = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensor.log.message.SensorLogMessage.prototype.hasEventMessage = function() {
  return jspb.Message.getField(this, 4) != null;
};


goog.object.extend(exports, proto.sensor.log.message);
